version: "3"
services:
  db:
    image: postgres
    container_name: gohub_db
    volumes:
      - psgl_data:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: gohub
      POSTGRES_PASSWORD: gohub_dev_password
    ports:
      - 5433:5432
  gohub_api:
    container_name: gohub_api # サービス名
    image: gohub_api # image名
    stdin_open: true # コンテナの標準入力をオープンしたままにする
    tty: true # コンテナに疑似TTYを割り当てる
    ports: # ホストOSのポートとコンテナのポートをつなげる
      - "8080:8080"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    volumes:
      - .:/go/src/app # マウントディレクトリ
volumes:
  psgl_data:
