version: "3"
services:
  # postgres database
  db:
    image: postgres
    container_name: gohub_db
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - psgl_data:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d # 「script/01_initialize.sql」を実行
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: gohub_dev_password
      TZ: Asia/Tokyo
    ports:
      - 5433:5432
  # SQL client tool
  # http://localhost:8000
  pgadmin4:
    image: dpage/pgadmin4:5.0
    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
      - pgadmin4_volume:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: gohub.api@sample.com
      PGADMIN_DEFAULT_PASSWORD: gohub_password
    hostname: pgadmin4
    depends_on:
      - db
    restart: always
  # API Aplication
  # http://localhost:8080
  gohub_api:
    container_name: gohub_api # サービス名
    image: gohub_api # image名
    stdin_open: true # コンテナの標準入力をオープンしたままにする
    tty: true # コンテナに疑似TTYを割り当てる
    ports: # ホストOSのポートとコンテナのポートをつなげる
      - "8080:8080"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/go/src/app # マウントディレクトリ
    environment:
      TZ: Asia/Tokyo
volumes:
  psgl_data:
  pgadmin4_volume:
    external: true
