version: "3"
services:
  gohub_api:
    container_name: gohub_api # サービス名
    image: gohub_api # image名
    tty: true # コンテナの永続化
    ports: # ホストOSのポートとコンテナのポートをつなげる
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app # マウントディレクトリ
